### ISSUE TITLE
Limpieza del proyecto

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#1]

**Comment by pr3ssh** [comment]
@CIECODE Se va a realizar una limpieza en los siguientes términos:
- Eliminación del blog
- Eliminación del foro
- Eliminación de los eventos
- Eliminación de las imágenes de usuarios (solo se quedarán para diputados)
- Eliminación de las tareas cron (se pasarán a tipi-engine)

**Comment by pr3ssh** [comment]
@CIECODE validamos toda esta limipieza? Creo que puede venir bien para ficalizar la actividad de la herramienta simplificándola.

**Comment by javipe** [comment]
Hola Pablo. 
Las tres primeras eliminaciones: ok.
La de los usuarios: necesito pensarlo. Por ver como "capitalizamos" la pequeña comunidad TIPI creada y por si aún pudiera tener sentido la existencia de "usuarios" registrados aunque ya no haya foro... ¿Te parece que pospongamos esa decisión?
Lo de las "tareas cron" estoy seguro que estoy de acuerdo, pero explícame en una frase qué es para que no te diga que sí como a los tontos ;)

**Comment by pr3ssh** [comment]
No me refiero a borrar usuarios registrados sino borrar la posibilidad de que ellos puedan subir imagen de perfil. Parece una tontería pero implica servicios externos o implementaciones internas.
Lo de las tareas cron se pasarán todas al engine para poder controlarlo mejor. Es todo aquello que se hace de forma automática por las noches.

**Comment by javipe** [comment]
Ah. Ok. Pues si las fotos complican, me parece bien suprimirlo.
