### ISSUE TITLE
El escrapeo ha detectado "preocupación" a pesar de que la expresión regular es \\bocupación

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#101]
Hola @pr3ssh,

He detactado un caso en el que el escrapeo ha etiquetado un acto erróneamente como Vivienda por emplear la palabra "preocupación" debido a que ha confundido con ocupación, a pesar de que la expresión regular es \bocupa.*\bcasa\b

Más que por este caso concreto, me preocupa mucho que no esté "respetando" la orden de \b porque entonces sí que estaríamos jodidos.

¿Se te ocurre alguna explicación por la que esto pueda ocurrir puntualmente?

Javi

**Comment by pr3ssh** [comment]
@CIECODE Raro! Me puedes decir cuál es?

**Comment by javipe** [comment]
Hola @pr3ssh 
Perdón, que ayer te contesté desde el bus y no te pasé ningún link concreto. Hay muchos ejemplos, pero el que yo vi era este: http://tipiciudadano.es/tipis/57eae668cc3072a4f1043ad7.
Detecta ocupación, cuando el texto sólo habla de preocupación y la expresión regular está bien escrita (\bocupación)

**Comment by javipe** [comment]
Hola @pr3ssh 
Este bug lo he comprobado y se sigue dando.
