### ISSUE TITLE
En la información que suministramos de cada acto, no damos el número de referencia

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#102]
Hola @pr3ssh 

Me he fijado, en la información que suministramos de cada acto parlamentario no ofrecemos en ningún sitio el número de referencia del mismo.

Resulta raro porque:
1. Es uno de los criterios de búsqueda que ofrecemos en nuestro buscador.
2. Es la forma en la que un usuario podría contrastar en la web del Congreso la información que damos en supuestos como el actual en el que el link que ofrecemos no está funcionando bien. 

¿Sería posible?

Javi

**Comment by pr3ssh** [comment]
@CIECODE Desde luego.
