### ISSUE TITLE
No obligar a pasar las páginas de los resultados de las búsquedas de una en una

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#103]
@pr3ssh 

Ahora mismo aún es manejable, porque hay pocos actos, pero en previsión de cuando haya 300 páginas, hay que prever el que puedas ir a cualquier páginas de las desplegadas para ofrecer los resultados de la búsqueda.

Javi

**Comment by pr3ssh** [comment]
En tal caso, ¿como sabes si ir a una u otra pagina por su número? Se pueden poner más iniciativas por página (como 50) pero el navegar es necesario o si no hay que afinar la busqueda o descargar los datos.

**Comment by javipe** [comment]
Hola @pr3ssh 
Me refiero a que si en algún momento hay 75 páginas tras una búsqueda puedas pasar de la 2 a la 35 sin necesidad de ir una a una. Es algo que tienen la mayoría de los buscadores, ¿no? Me suenan dos opciones habituales:
1. Que diga "Pág. 4 de 50" y que puedas meter cualquier número en lugar del 4.
2. Que además de decirte en qué página estás, ponga algo como: "Primera >>>> Siguiente>>>> Última".
No es algo que me obsesione para hoy, pero sí que puede llegar a ser un incordio en un breve cuando aumente la actividad y por tanto el número de iniciativas.
Lo hablamos.
Javi

**Comment by pr3ssh** [comment]
@CIECODE Si, si te parece lo hablamos sí. Asi es como estaba hecho antes pero lo cambiamos para mejorarlo. No entiendo el interés en poder ir a una página intermedia (sin saber lo que te vas a encontrar alli), aunque si entiendo el interés de ir a la última o volver a la primera. Te parece que metamos eso? Daría solucion a lo que comentas?

**Comment by pr3ssh** [comment]
@CIECODE Nos vale con "ir a la última o volver a la primera"?

**Comment by javipe** [comment]
Hola @pr3ssh 
Te refieres a que si estás en la pág.5, por ejemplo, puedas volver a la 4, pasar a la 6 y, ADEMÁS, "ir a la última o volver a la primera"?

Si lo he entendido bien, sí me parece bien.

Javi
