### ISSUE TITLE
¿Visteis los tips de búsqueda que os pasé el lunes?

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#104]
Hola @pr3ssh , 
¿Viste los tips de búsqueda que te pasé el lunes por la tarde?
Te lo comento por si se te hubiera traspapelado.
Si lo fueras a implementar, añadiría una cosa más:
"Si al acceder a la web del Congreso de los Diputados desde TIPI no se carga la página, se soluciona si refrescas el buscador".

**Comment by javipe** [comment]
Están en el issue #44

**Comment by pr3ssh** [comment]
Duplicada por la #44
