### ISSUE TITLE
Compartir permisos para acceder al Google Analytics de TIPI

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#105]
Buenos días @pr3ssh 
Hace un rato te he mandado la invitación para acceder al Google Analytics de TIPI, con permisos para trastear y editar.
Es una herramienta que controlo muy poco, así que si nos ayudas a adecentarla un poco para que nos sea útil para el seguimiento del movimiento de la página, genial.
Por lo que he visto, el pico de visitas fue el lunes con 100 aprox y luego se ha mantenido entre las 80 y las 45 el resto de días. 
No es mucho, pero es que aún no hemos comenzado con la difusión como Dios manda. A ver si mantenemos un buen ritmo de visitas. 
Un abrazo.
Javi

**Comment by pr3ssh** [comment]
@CIECODE Poco te puedo ayudar ya que soy usuario de consulta y no de saberlo administrar bien bien.

**Comment by javipe** [comment]
Bueno, pues ya iremos aprendiendo. Voy a preguntar en mi entorno si alguien sabe y me puede contar un par de pistas.
