### ISSUE TITLE
En la página temática de Transparencia y Acceso a Información no aparece la información sobre los 3 diputados más activos

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#107]
Hola @pr3ssh 
- Transparencia y Acceso a Información: http://tipiciudadano.es/temas/transparencia-y-acceso-a-informacion

**Comment by joseEnrique** [comment]
Hola @CIECODE ,

En ese término realmente no tiene diputados,hay grupos o alguien ajeno al congreso(externo). Por lo que no debe salir

**Comment by javipe** [comment]
Ah, ok! Genial, entonces.
