### ISSUE TITLE
Repensar acceso a "perfil" de un diputado o de grupo parlamenatario

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#108]
Hola @pr3ssh , 
Ayer nos empezó a seguir en Twitter un diputado y cuando fui a mandarle su perfil, vi que no hay forma de llegar pro-activamente al perfil de un diputado si no está en ese momento entre los tres más destacados de alguno de los temas.
Creo que esto supone un limitante grande a la hora de establecer interacción con los diputados o para los usos que un usuario cualquier quiera hacer de TIPI en relación con los diputados.
¿Cómo se os ocurre que hagamos esto?
Tengo varias ideas "de compromiso", pero creo que habría que pensarlo bien para ofrecerlo adecuadamente.
Lo hablamos
Javi
PD: dudo si ponerlo como bug o como enhancement... Lo pongo como pregunta por ahora.

**Comment by pr3ssh** [comment]
Gracias por abrir esto. Es algo que yo si sabía pero no he tenido tiempo de plantearlo. Creo que la opción más potente es enlazar los diputados cada vez que aparezcan, ya sea en el buscador o en la ficha de una iniciativa. Te parece? Lo mismo con los grupos parlamentarios.

**Comment by javipe** [comment]
Hola!
Sí, para cuando aparecen en la ficha de una iniciativa lo veo claro. 
La duda me surge cuando se llegue a través del buscador, porque la interfaz normal sería la del resultado de una búsqueda (dado que han podido buscar por Diputado + Infancia, por ej ) lo cual no es compatible con la ficha general del diputado. Lo único que se me ocurre es que esa fiche se muestre cuando en el buscador sólo se use en diputado como criterio de búsqueda (sin tema, ni nada)... ¿Como lo ves?

**Comment by pr3ssh** [comment]
No me refiero a que el buscador arroje iniciativas en ciertas búsquedas y
diputados en otras. Eso sería un gallo de diseño notable. Más bien me
refiero a que cuando hagas una búsqueda y aparezcan iniciativas con
diputados como autores, que esos diputados sean enlazables a sus propias
páginas.

Pablo Martín Muñoz
Hacker Cívico

**Comment by javipe** [comment]
Hola,
Organicemos la discusión por partes:
- A: los dos estamos de acuerdo en enlazar al espacio del diputado cuando aparezca en una iniciativa. En esto, adelante cuando quieras/puedas.
  -B: no he entendido bien, entonces, a que te referías en tu primera respuesta a "cuando aparezcan en el buscador".
- Si sólo implementamos A, la única forma que ofrecemos al usuario para acceder a la ficha del diputado es: hacer una búsqueda en el buscador + abrir una ficha + clickar en el nombre del diputado. Habría que encontrar una forma de hacerlo más directo. Se puede quedar como enhancement, pero habrá que hacerlo en algún momento.

**Comment by pr3ssh** [comment]
Se podria mostrar una vez has hecho una busqueda por alguno de ellos (como un bloque superior antes de las iniciativas).

**Comment by javipe** [comment]
Esto se quedó abierto, pero ya está solucionado. Lo cierro.
Javi
