### ISSUE TITLE
Resolver colapsado menú en móviles

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#109]

**Comment by pr3ssh** [comment]
[Chequear este enlace](https://github.com/twbs/bootstrap/issues/4497)

**Comment by javipe** [comment]
Hola @pr3ssh 
¿Cómo de relevante consideras tú que es esto? No tengo ni idea y no sé si hay que priorizarlo o no.
Javi

**Comment by pr3ssh** [comment]
Yo diría que sí y no debe ser demasiado compleja. Lo intenté hace un tiempo cuando me di cuenta pero no pude sacarlo. Tendría que verlo con más detenimiento pero no implicaría mucho.
