### ISSUE TITLE
El acto 161/000155 genera matches con términos que no contiene en su texto

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#110]
Hola @pr3ssh,
El acto 161/000155 (http://www.tipiciudadano.es/tipis/57eae536cc3072a4f1042d3f) genera matches con términos que no contiene y, por tanto, etiqueta diccionarios erróneamente. De hecho, creo que no contiene ninguno de los términos que detecta.
¿Alguna explicación por la que se haya generado este problema?
Javi

**Comment by joseEnrique** [comment]
He mirado mongo y el texto está bien rescatado, se puede descartar el scrap

**Comment by javipe** [comment]
Buenas noticias, @pr3ssh este acto ha desaparecido de TIPI, por lo que un tema menos.
