### ISSUE TITLE
El buscador ha considerado dos actos parlamentarios consecutivos como uno único

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#111]
Hola @pr3ssh,
El buscador considera como parte del acto 162/000122 el texto del siguiente 162/000123 y por lo tanto hace match al primero de los actos con la "mutilación genital femenina", que es citada en el segundo de los actos.
http://www.tipiciudadano.es/tipis/57eae64fcc3072a4f10439b1
¿Alguna razón por la que este tipo de errores se puedan estar dando?
Javi

**Comment by joseEnrique** [comment]
@CIECODE estaba cogiendo texto que no debía, solucionado. Cualquier comportamiento raro no dudes en comentarlo. 

Un Saludo. Quique

**Comment by javipe** [comment]
Genial, 

Sobre todo en estas primeras semanas en las que el volumen de info aún es manejable, iremos haciendo revisiones exhaustivas de los resultados para detectar errores.

Abrazo.

Javi
