### ISSUE TITLE
Instrucciones para introducir a través del Admin las correcciones en los diccionarios

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#112]
Buenos días @pr3ssh 
Ya tenemos un buen número de correcciones de los diccionarios (hemos revisado los primeros 6-7 diccionarios y hemos detectado unas cuantas mejoras que reducirán gran parte de los posibles falsos positivos que se han dado ahora). 
Ayer estuve ojeando la pág del Admin de TIPI y parece fácil la cosa.
Tengo dos preguntas antes de ponerme a introducir los cambios:
1. He visto que en ningún término estaba activada la opción "Shuffle". No sé si es porque aún no se implementó. Si fuera así, dímelo y nos ponemos a hacerlo hoy mismo desde CIECODE.
2. Una vez estén introducidas las revisiones, lo ideal sería correr la base de datos otra vez desde el inicio, como hablamos. Sé que me dijiste que lo ideal es hacer esto durante el fin de semana, supongo que para aprovechar que hay menos visitas. Mi duda es si merece la pena hacerlo antes de tu sesión en Visualizar y de mi participación en el GIGAPP, que atraerán muchas visitas, para que lo vean ya sin los errores actuales.
Javi

**Comment by pr3ssh** [comment]
Creo que la mejor opción es hacerlo directamente en el administrador sí para poder lanzarlo todo al instante. Hay un problema con los shuffle y es que están puestos en la base de datos como 0 o 1 cuando deben ser true o false. En el procesado han ido bien pero en la interfaz salen mal. Se pueden revisar todos confirme se revisan los términos. Podéis? Mil gracias.

En cuanto esté todo me avisas y esta tarde lanzamos todo.

**Comment by javipe** [comment]
Hola @pr3ssh , 
Pero en el formulario no hay opción de escribir nada, sólo de clickar o no clickar. ¿Sería hacer eso para todos los diccionarios? ¿En caso de que sea "1" clickamos y en caso de que sea "0", no?
Un abrazo.
Javi

**Comment by javipe** [comment]
Hola @pr3ssh 
Una última pregunta antes de ponernos a introducir los cambios. He visto que en el "formulario" de los diccionarios, las palabras que nosotros teníamos con \ están escritos con una única \ ¿Es así? ¿Borramos la doble \ al transcribirlo? ¿Alguna advertencia más?

**Comment by pr3ssh** [comment]
@CIECODE Aqui ya lo escribes con una barra sola y el se encarga de guardarlo con dos barras (tal y como necesitamos).
Ahora mismo creo que no, ya te digo, el repasar los shuffles

**Comment by javipe** [comment]
Ok. Pues a por ello!!!

**Comment by javipe** [comment]
Hola @pr3ssh 
En media hora aproximadamente habré acabado de subir las modificaciones de los diccionarios que hemos podido revisar hasta hoy. Son muchas mejoras, por lo que creo que merece la pena correr de nuevo la base de datos, aunque aún falte la segunda mitad de los diccionarios por revisar en los próximos días.
En cuanto acabe te escribo para que lo sepas.
Javi

**Comment by javipe** [comment]
Hola @pr3ssh 
Ya están revisados. Y en 8 de los 21 también está incorporado la info del shuffle. En el resto no. Es algo que haremos lo antes posible, porque sabemos que sin el shuffle, estaremos generando falsos negativos seguro.
Un abrazo.
Javi
