### ISSUE TITLE
En la página temática de Educación, no salen los "últimos actos" debajo de los diputados

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#113]
Hola @pr3ssh 
Ahí va el link: http://tipiciudadano.es/temas/educacion
Hemos tenido la mala suerte de que el tuit de primera mañana citando a los 3 diputados más activos, lo he hecho sobre educación y justo en este tema no vienen los diputados más activos.
¿Lo podéis mirar, please?
Javi

**Comment by joseEnrique** [comment]
@pr3ssh cuando se accede a /api/v1/stats/latest/educacion da error. Solo pasa en ese endpoint. ¿Tiene que ver con que no salga en esta vista?

**Comment by pr3ssh** [comment]
@joseEnrique Haz una query a las estadísticas y muestra el campo 'latest' para ver qué pasa con educación. Es como si tuviera los objetos pero están vacios por lo que cuando se quiere acceder a sus valores el sistema falla.

**Comment by pr3ssh** [comment]
Está duplicada por la #125
