### ISSUE TITLE
¿Cuándo comenzarán a llegar las alertas de TIPI por email a los usuarios?

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#114]

**Comment by joseEnrique** [comment]
@CIECODE habia un error de código que ya esta solucionado

**Comment by javipe** [comment]
Hola @joseEnrique 
Este issue se cerró hace 7 días pero creo que aún no están llegando los correos a los usuarios logueados, no? (al menos a mi como usuario no me están llegando).
¿Cómo está este asunto?
Javi

**Comment by joseEnrique** [comment]
Buenas @CIECODE 

puede ser que no se haya encontrado ningún TIPI más y como no son nuevas las que ya están, pues no se manda nada. 

Está testeado de forma que si hay, la manda. Había unos problemas con Sparkpost, pero se solucionó el Lunes

**Comment by pr3ssh** [comment]
Por si aporta algo: http://tipiciudadano.es/escaner?dicts=&terms=&grupootro=&autor=&fechadesde=10%2F10%2F2016&fechahasta=13%2F10%2F2016&lugar=&ref=&vtipo=&tramitacion=&titulo=

En tal caso seguimos pendientes de que su funcionamiento sea el correcto.

**Comment by javipe** [comment]
Ok. 
O sea, en teoría desde el lunes ya deberían estar entrando notificaciones de los nuevos actos?
Suponiendo que haya actos nuevos de la temática a la que estés suscrito, cada cuanto se mandan las notificaciones? Siempre que haya novedad o se podría programar para que fuera semanal, por ejemplo? Es por no spamear en exceso a los usuarios. 
Javi

**Comment by joseEnrique** [comment]
@CIECODE solo se avisa en el caso de que haya nuevos, después no se envían mas correos hasta el siguiente que encuentra.

De momento se comprueba cada dos días y no se puede cambiar debido a que está asociado a las tareas del backend

**Comment by javipe** [comment]
Ok. Gracias!
¿Os parece que dejemos el issue abierto hasta que lleguen las notificaciones?

**Comment by joseEnrique** [comment]
@CIECODE Perfecto!!
