### ISSUE TITLE
El scanner y las estadísticas de la home no están funcionando

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#117]
Hola @pr3ssh @joseEnrique @pablovg2 

Después del escrapeo de anoche el scanner y las estadísticas de la home no están funcionando. Supongo que era uno de los escenarios posibles. Sólo os aviso por si hubiera algo fácil que hacer para solucionarlo. Si no y el fallo se prolongara, ¿hay alguna forma de "apagar" la página hasta que se solucione?

Un abrazo.

Javi

**Comment by pr3ssh** [comment]
@CIECODE Lo estamos lanzando todo. Había un pequeño fallo en los diccionarios.
