### ISSUE TITLE
URL para compartir resultados en redes sociales

### ISSUE THREAD

**Issue by pablovg2** [CIECODE-Madrid/tipi#121]
Al copiar una url de una búsqueda del escaner y compartirla en redes sociales, se puede generar errores al no tratar correctamente los parámetros vacíos. 

Ejemplo:
url completa: http://tipiciudadano.es/escaner?dicts=&terms=&grupootro=&autor=Garc%C3%ADa+Sempere%2C+Eva&fechadesde=&fechahasta=&lugar=&ref=&vtipo=&tramitacion=&titulo=

Al pegarla en Facebook la url que se genera en el enlace es: http://tipiciudadano.es/escaner?dicts&terms&grupootro&autor=Garc%C3%ADa%20Sempere%2C%20Eva&fechadesde&fechahasta&lugar&ref&vtipo&tramitacion&titulo

Posibles soluciones:
- Añadir un botón de compartir la url que copie sólo la url con los parámetros introducidos (no nulos)
  ej: http://tipiciudadano.es/escaner?autor=Garc%C3%ADa+Sempere%2C+Eva

**Comment by javipe** [comment]
Hola @pr3ssh ¿esto ya está solucionado, verdad? Confírmamelo, please y, si es el caso, lo cerramos.
Javi

**Comment by pr3ssh** [comment]
@CIECODE No realmente. Es un problema al compartir en Facebook ya que en Twitter y en otros medios parece que no hay problema. Si te parece lo metemos en el milestone. Ya me dices.

**Comment by javipe** [comment]
Ok.
Lo metemos en el Milestone, pendiente de decidir si va a ir priorizado o no.

Javi

**Comment by spolpen** [comment]
@CIECODE Hay que configurar correctamente la API de FB que está integrada, ¿está registrada por vosotros? 
La ID es `1662188644096441`

**Comment by javipe** [comment]
Hola @spolpen 
Sí, está configurada por nosotros. Estamos en la página de devolpers de Facebook. Dinos qué tenemos que hacer desde aquí.

**Comment by spolpen** [comment]
Hola @CIECODE,

Ahora mismo una URL que se genera para compartir contenido desde TIPI es p.ej. [https://www.facebook.com/dialog/feed?app_id=1662188644096441&link=http%3A%2F%2Ftipiciudadano.es%2Ftemas%2Fvivienda&name=Consulta%20lo%20%C3%BAltimo%20sobre%20vivienda%20en&description=undefined&redirect_uri=http%3A%2F%2Ftipiciudadano.es%2Ftemas%2Fvivienda](https://www.facebook.com/dialog/feed?app_id=1662188644096441&link=http%3A%2F%2Ftipiciudadano.es%2Ftemas%2Fvivienda&name=Consulta%20lo%20%C3%BAltimo%20sobre%20vivienda%20en&description=undefined&redirect_uri=http%3A%2F%2Ftipiciudadano.es%2Ftemas%2Fvivienda)

Indica que la aplicación está aún en desarrolllo, que debe ser una opción de la API como **Developer Mode**. Si no, podéis indicarnos los credenciales por correo electrónico y la configuramos correctamente.

**Comment by javipe** [comment]
Hola @spolpen 
Hemos entrado en revisión de aplicación y hemos pasado la aplicación a "Activa". Dice que la aplicación está actualmente activa y disponible para el público. Dinos si con esto ya está solucionado.
