### ISSUE TITLE
El campo "actos relacionados" dentro de una iniciativa: ¿no debería ser un campo activo para poder acceder a él directamente?

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#123]
Hola @pr3ssh y @joseEnrique,

Os paso un ejemplo: http://www.tipiciudadano.es/tipis/57f61d0dcc307247c4b45438

Aparece que hay Enmiendas del Grupo Popular a esta Proposición No de Ley, pero no permite ir a ella directamente, ni damos ninguna pista sobre cómo hacerlo.

Javi

**Comment by pr3ssh** [comment]
@CIECODE En ese caso, y como quedamos, se muestra pero no se enlaza porque no es tipi. Esto es, mostramos todo pero solo enlazamos lo tipi.

**Comment by javipe** [comment]
Ah, ok!
