### ISSUE TITLE
Ha desaparecido un usuario de la lista tras editar yo su información!!

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#124]
Hola, 

Acabo de entrar a la página de Administración de TIPI para actualizar la info de Ramiro Viñuales (cambiar su email de contacto y darle permisos de administrador) y al darle a Update, ha desaparecido de la lista de usuarios y no puede acceder.

¿Sabéis cómo revertir la situación o cómo solucionarlo?

Mil gracias.

Javi

**Comment by pr3ssh** [comment]
@CIECODE Lo veo como usuario del sistema. Ahora, no se si puede entrar o no porque no tengo su clave. Si no puede entrar me lo dices y la actualizamos.

**Comment by javipe** [comment]
Hola @pr3ssh.
¿Me ayudas a solucionar esto, que tengo al pobre Ramiro sin usuario desde hace unas semanas? Lo ideal sería recuperar su usuario (ramiro.vinuales@ciecode.es). Yo ahora mismo no lo veo en la lista de usuarios, por lo que no sé si basta con que le reenviemos una contraseña nueva o si debería hacer algo más. Ha intentado darse de alta de nuevo y no puede.
Abrazo.
Javi

**Comment by pr3ssh** [comment]
Cierro esta y la pasamos a #159
