### ISSUE TITLE
Cambio de un diputado de C's

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#126]
Hola, 

Me acabo de enterar de que el diputado Domingo Lorenzo de C's ha dimitido y le sustituye Sandra Julià. 
Link a la noticia: http://www.abc.es/espana/comunidad-valenciana/abci-dimite-domingo-lorenzo-diputado-ciudadanos-castellon-congreso-201610101223_noticia.html

Domingo Lorenzo sólo era autor de un acto TIPI hasta la fecha (y era un acto compartido con otro diputado): http://tipiciudadano.es/tipis/57f505becc3072c7615c5d2a

Tenemos que ver cómo proceder en estos casos ya que, aunque no ocurra todos los días, no es del todo infrecuente.

El tuiter de la nueva diputada: @MSandraJulia

Javi

**Comment by javipe** [comment]
El link de su perfil en el Congreso:
http://www.congreso.es/portal/page/portal/Congreso/Congreso/Diputados/BusqForm?_piref73_1333155_73_1333154_1333154.next_page=/wc/fichaDiputado?idDiputado=354&idLegislatura=12

**Comment by pr3ssh** [comment]
@joseEnrique Puedes revisar esto? Es para saber que el escrapeo por diputados esta funcionando.

**Comment by pr3ssh** [comment]
Ps.: La han dado de alta hoy

**Comment by pr3ssh** [comment]
Actualizada!
