### ISSUE TITLE
El acto 162/000125 no "respeta" la expesión regular y detecta independencia en lugar de dependencia

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#127]
Hola @pr3ssh 

En el acto 162/000125 salta la expresión Recortes en dependencia (expresión regular: \bdepend.*\brecort) pero la palabra dependencia no existe en el texto. Sí existe independencia.

Otra opción es que unos pocos actos más abajo, sí se habla de "dependencia" por lo que no sé si se habrá ido a otros textos o es que no está respetando el \b.

Link: http://10.0.0.50/tipis/57f506b3cc3072c7615c654a

Javi

**Comment by javipe** [comment]
Hola @pr3ssh 
Este tema sigue siendo bug, porque se sigue detectando dependencia en "independencia" a pesar de que la expresión regular exige que existe un espacio antes de "dependencia".

**Comment by pr3ssh** [comment]
@CIECODE Con esta ahora mismo no sé si pasaba lo mismo que con las otras y la expresión regular estaba bien construida.

**Comment by javipe** [comment]
Hola. Lo miro y te digo. Javi

**Comment by javipe** [comment]
Hola. 
Ya está revisado. Detecta correctamente "dependiente", a pesar de no ser con el sentido semántico correcto. 
Procedo a cerrar el bug. 
Javi
