### ISSUE TITLE
 Meter nueva columna actualizacion y mostrar esa en el escaner (En la ficha de la iniciativa se muestran las dos fechas)

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#132]
Hola @pr3ssh @joseEnrique 
Creo que no he entendido bien cómo va el tema de la frecuencia de actualización de actos TIPI y cómo se relaciona con la publicación de info por parte del Congreso de los Diputados.
Ahora mismo (ver imagen inferior) parece que los días 11-13 y 14 de octubre se publicaron nuevos Boletines por parte del Congreso. Si nuestro escrapeo ocurre cada 48h y siendo hoy día 17, todos estos boletines deberían estar ya en nuestro buscador y no es así.
![image](https://cloud.githubusercontent.com/assets/13982071/19426886/63a8fc94-9440-11e6-9e88-4ba84711a1d0.png)
Me podéis volver a contar cómo va este tema, que igual me estoy olvidando yo de algo.
Al respecto se me ha ocurrido una idea (poner en el escáner la info de cuándo ha sido la última actualización) que desarrollo en otro issue para no mezclar conversaciones.
Abrazo.
Javi

**Comment by joseEnrique** [comment]
@CIECODE puedes pasarme esa url del congreso?

**Comment by javipe** [comment]
Ahí va @joseEnrique 
http://www.congreso.es/portal/page/portal/Congreso/Congreso/Iniciativas?_piref73_2148295_73_1335437_1335437.next_page=/wc/servidorCGI&CMD=VERLST&CONF=BRSPUB.cnf&BASE=PU12&FMT=PUWTXLTS.fmt&DOCS=76-83&DOCORDER=FIFO&OPDEF=Y&QUERY=%28B%29.PUBL.+%26+%28CONGRESO%29.SECC.

**Comment by javipe** [comment]
Perdón, que no le había quitado los últimos caracteres:

http://www.congreso.es/portal/page/portal/Congreso/Congreso/Iniciativas?_piref73_2148295_73_1335437_1335437.next_page=/wc/servidorCGI&CMD=VERLST&CONF=BRSPUB.cnf&BASE=PU12&FMT=PUWTXLTS.fmt&DOCS=76-83&DOCORDER=FIFO&OPDEF=Y&QUERY=%28B%29.PUBL.+%26+%28CONGRESO%29.

**Comment by joseEnrique** [comment]
@CIECODE  A ver, el escrapeo de los boletines no se hace íntegramente, si no que en la página de una iniciativa cogiendo el enlace que ellos facilitan y con algunos filtros y accede via web para extraer el trozo que le pertenecen. El problema estaría cuando actualiza, que no se actualiza todo los textos, solo los que acordamos que era importante tenerlos.

**Comment by javipe** [comment]
Ok @joseEnrique 
De hecho, estoy viendo ahora que algunas de las actualizaciones de "estado de tramitación" que ofrecemos en el escáner ya recogen las modificaciones de lo publicado el día 14 de octubre. 
Por ejemplo, el acto: http://tipiciudadano.es/tipis/57f61d70cc307247c4b455e9 aparece en el escáner con fecha de 10 de agosto (día en el que fue publicada la iniciativa) y nosotros ya ofrecemos la info de que este viernes 14 de octubre fue aprobada, pero para el usuario no hay forma de saber que ese acto parlamentario ha sufrido modificaciones.
Tenemos que pensar, por tanto, en la forma de mostrar ese dinamismo y actualidad que ofrece TIPI, porque tal y como está ahora no se percibe. Se me ocurre que el escáner ofrezca una 5ª columna que se llame 'última actualización' o algo así que, en este caso, sería el 14/10/2016, fecha en la que el acto ha sufrido un cambio en su estado de tramitación.
¿Cómo lo veis?
Javi

**Comment by pr3ssh** [comment]
@CIECODE Lo veo bien pero iría quitando otra columna para no saturar.

@joseEnrique Te parece que metamos una columna **ultima actualzacion** en la que guardemos la fecha de creación (al principio) y luego la de actualización se actualice lo que se actualice? Cuando esté esto (habra que relanzar todo) lo metemos en el escaner y en la ficha.

**Comment by pr3ssh** [comment]
Poner en la celda la fecha de última actualización: (ult. act. xx/xx/xxxx)

**Comment by pr3ssh** [comment]
DEFINITIVO:
Se mete nueva columna **actualizacion** y siempre se muestra esa en el escaner y siempre se ordena por esa columna. En la ficha de la iniciativa se muestran las dos fechas.

**Comment by javipe** [comment]
Trato hecho!

**Comment by javipe** [comment]
Hola @pr3ssh 
¿Cómo va esto? ¿Ha habido alguna complicación respecto a lo que hablamos? Es sólo por hacer recapitulación de asuntos pendientes.
Abrazo.
Javi

**Comment by pr3ssh** [comment]
Creo que lo tendremos listo en el proximo lanzamiento ya que ya esta implementado. Lo que haremos luego es mostrarlo en la web de forma bonita ;)
