### ISSUE TITLE
Añadir un "Última actualización realizada el día dd/yy/aaaa" en la página del escáner

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#133]
Hola @pr3ssh @joseEnrique , 
Creo que sería muy útil ofrecer al usuario la info sobre cuándo ha sido la última actualización de información por parte de TIPI. 
Al menos en la página principal del escáner, pero si se pudiera, también en cualquiera de las páginas en las que ofrezcamos info de actos parlamentarios.
Ahora mismo es un poco confuso y para usuarios frecuentes es un rollo no saber si lo que estás viendo es nueva info o si son ya actos conocidos.
¿Es posible? Lo pongo como enhancement.
Javi

**Comment by javipe** [comment]
Hola @pr3ssh este issue ya está tratado en el otro hilo al que acabo de responder (en el que quedamos en que la columna de fecha del escáner se pasaría a llamar última actualización de modo que muestre la fecha de registro hasta que ocurra algo posterior y a partir de ahí, la fecha de dicha modificación). Si te parece, cerramos este issue y dejamos el otro, al que voy a cambiar el nombre para sea más claro a qué nos referimos.
Javi

**Comment by pr3ssh** [comment]
@CIECODE Ok
