### ISSUE TITLE
En el buscador del escáner no aparece como tipo de acto las "Enmiendas a Proposiciones no de Ley"

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#134]
Hola @pr3ssh y @joseEnrique 
Me he dado cuenta de que en el buscador no tenemos como tipo de acto las "Enmiendas a proposiciones no de ley", siendo éstas uno de los tipos de actos más frecuentes en la actividad del Congreso de los Diputados.
Y no sé si el problema es sólo del buscador o que no las estamos teniendo en cuenta en el escrapeo, dado que he encontrado una Proposición no de Ley que sí tenemos registrada y etiquetada y en cuyas enmiendas aparecen términos TIPI (por lo que debería haberse etiquetado) y no aparece.

![image](https://cloud.githubusercontent.com/assets/13982071/19427688/e1480528-9445-11e6-86de-62f86f50e2cd.png)

Se trata del acto 162/000113 (http://tipiciudadano.es/tipis/57f61d0fcc307247c4b45448). Las enmiendas de Podemos, al menos, mencionan varios términos nuestros (http://www.congreso.es/portal/page/portal/Congreso/PopUpCGI?CMD=VERDOC&CONF=BRSPUB.cnf&BASE=PU12&PIECE=PUWC&DOCS=1-1&FMT=PUWTXDTS.fmt&OPDEF=Y&QUERY=%28B%29.PUBL.+%26+%28CONGRESO%29.SECC.+Y+BOCG-12-D-33.CODI.#(Página9): 

"A la Mesa del Congreso de los Diputados 
Al amparo de lo establecido en el Reglamento de la Cámara, el Grupo Parlamentario Confederal de Unidos Podemos-En Comú Podem-En Marea presenta las siguientes enmiendas parciales a la Proposición no de Ley para paralizar la aplicación y desarrollo de la LOMCE (Ley Orgánica 8/2013, de 9 de diciembre, para la mejora de la calidad educativa) con el fin de derogarla y de derogar el Real Decreto 310/2016, por el que se regulan las evaluaciones finales de ESO y Bachillerato, presentada por el Grupo Parlamentario Mixto, a instancias del Diputado del Partit Demòcrata Català don Francesc Homs i Molist. 

Enmienda 
De adición. 
Se añade un nuevo apartado 3 con la siguiente redacción: 
"3 (nuevo). Frenar el aumento del fracaso escolar, la segregación temprana y la expulsión del alumnado de los centros, desarrollando las siguientes actuaciones: 
- Evitar la doble vía en el cuarto curso de la Educación Secundaria Obligatoria (ESO), que impide para muchos alumnos/as la posibilidad de cursar Bachillerato. 
- Recuperar la diversificación curricular (prolongación del Programa de mejora del aprendizaje y rendimiento, PMAR) en cuarto de la ESO con la posibilidad de titulación. 
- Posibilitar la titulación de quienes sigan o hayan seguido los programas de Formación Profesional básica (FPB) y paralización de la misma. 
- Derecho a la educación de los/as jóvenes con diversidad funcional, aunque hayan cumplido veintiún años, para que no queden fuera del sistema educativo. 
- Eliminar las Evaluaciones finales de etapa de la LOMCE y los rankings. 
- Supresión de las subidas de tasas universitarias, realizadas a partir de 2012, y modificación de la política de becas con el aumento de las mismas. 
- Paralización del 3+2 en las universidades." 

Motivación. 
Necesidad de articular medidas urgentes para el curso 2016-2017, para su inmediata puesta en práctica, recogiendo la demanda de la comunidad educativa y organizaciones sociales, políticas de padres y madres, así como de estudiantes, que exigen un acuerdo que evite el aumento del fracaso escolar". 

Por favor, mirar a ver qué ha pasado con este tipo de acto parlamentario.
Javi

**Comment by pr3ssh** [comment]
@joseEnrique Puedes revisar esto?

**Comment by javipe** [comment]
Hola @joseEnrique vamos a agrupar varios isuues similares en uno nuevo así que cierro este.
