### ISSUE TITLE
Revisar huecos en blanco de comercio internacional (y quizá otros)

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#137]

**Comment by javipe** [comment]
Hola @pr3ssh 
Son 4 los diccionarios con huecos en blanco:
1. Comercio Internacional.
2. Dependencia.
3. Población reclusa.
4. Sanidad.

Javi

**Comment by pr3ssh** [comment]
Creo que ya no nos preocupa demasiado ya que se está controlando. Es verdad que quedan mal pero no es bloqueante.

**Comment by javipe** [comment]
Hola.
Esto se solucionó, pero nunca se cerró.
Una cosa menos.
Javi
