### ISSUE TITLE
¿Como puedo re-ordenar por orden alfabético los diccionarios después de las revisiones?

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#142]
Hola @pr3ssh 

En alguna ocasión, durante las revisiones, hemos introducido algún término nuevo, que se muestra en la última posición de los diccionarios, sitio en el que se ubica por defecto.

Habría que introducirlos en el lugar que les corresponda por orden alfabético, como el resto, pero ahora mismo no sé si es posible, porque la pestaña de "+" para introducir términos sólo está en la parte inferior de cada diccionario.

¿Se os ocurre alguna solución?

Javi

**Comment by pr3ssh** [comment]
Si te parece los dejamos en la base de datos desordenados y en cada sitio de la web que se muestren lo hacemos de forma ordenada. Los sitios son en la ficha de un diccioanrio, al mostrar terminos, y en el selector del escaner.

**Comment by javipe** [comment]
Hola @pr3ssh 
Me parece perfecto. 
Javi
