### ISSUE TITLE
El link de un acto parlamentario lleva a un sitio erróneo en la web del Congreso

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#143]
Hola @pr3ssh y @joseEnrique 
He encontrado un acto cuyo link lleva a un destino erróneo en la web del Congreso.
El acto TIPI es el siguiente: http://www.tipiciudadano.es/tipis/57f506b7cc3072c7615c6566.
Lleva al siguiente destino del Congreso: http://www.congreso.es/portal/page/portal/Congreso/Congreso/Iniciativas/Indice%20de%20Iniciativas?_piref73_1335503_73_1335500_1335500.next_page=/wc/servidorCGI&CMD=VERLST&BASE=IW12&PIECE=IWC2&FMT=INITXD1S.fmt&FORM1=INITXLUS.fmt&DOCS=57-57&QUERY=%28I%29.ACIN1.+%26+%28162%29.
- Cuando el correcto debería ser: http://www.congreso.es/portal/page/portal/Congreso/Congreso/Iniciativas?_piref73_2148295_73_1335437_1335437.next_page=/wc/servidorCGI&CMD=VERLST&BASE=IW12&PIECE=IWC2&FMT=INITXD1S.fmt&FORM1=INITXLUS.fmt&DOCS=1-1&QUERY=%28I%29.ACIN1.+%26+%28162%2F000130%29.

**Comment by pr3ssh** [comment]
Fallo de ellos. Ya funciona bien.
