### ISSUE TITLE
Incidencia con la suscripción de un nuevo usuario

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#145]
Buenos días @pr3ssh 
Nos ha escrito a través de FB un nuevo usuario (alejandrocortina@acoge.org) pidiendo ayuda porque el sistema no le deja darse de alta.
Lo he intentado yo internamente desde Admin y me salta este mensaje
![image](https://cloud.githubusercontent.com/assets/13982071/19547884/3c29b4da-969b-11e6-8521-038ad626cac2.png)
Por favor, echadle un vistazo, porque sospecho que hay algo que no está funcionando bien, porque llevamos 2 días con muchas visitas a la web y desde el lunes no hay ningún nuevo usuario, por lo que quizá esté dando error el formulario de inscripción.
Gracias.
Javi

**Comment by pr3ssh** [comment]
Lo del error desde el admin es lógico porque no tenemos sistema de envío de correos ahora mismo desde la web (ya que las alertas se envían desde **tipi-engine**.
Acabo de crearme un usuario en la web sin problemas dándome de alta en el formulario (desde Chrome y desde Firefox).

**Comment by javipe** [comment]
Ok @pr3ssh pues le voy a comentar que lo vuelva a intentar a ver si fue algo puntual o algo.

**Comment by pr3ssh** [comment]
Cierro y si hay otra cosa la volvemos a abrir.

**Comment by javipe** [comment]
Hola @pr3ssh, 

Esto es lo que me comentó ayer por FB el usuario que tuvo problemas para registrarse:

"Utilizo firefox. El mensaje de error es el siguiente «username failed regular expression validation»
Pero lo acabo de conseguir.
El error puede estar en que, en algunos campos, no se permiten espacios o acentos. Por ejemplo en «tu perfil», en el apartado organización. O en el acceso, en apartado nombre de usuario".

¿Puede ser que esté en lo cierto? Si es así, deberíamos avisarlo de algún modo. ¿Te parece?

Javi
