### ISSUE TITLE
El link al Congreso de un acto lleva al lugar equivocado

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#146]
Hola @pr3ssh @joseEnrique 

El link que ofrecemos al Congreso del acto http://www.tipiciudadano.es/tipis/57f506b8cc3072c7615c6576 conduce a un lugar equivocado de la web del Congreso.

Javi

**Comment by pr3ssh** [comment]
@joseEnrique Sabemos a qué puede ser debido?

**Comment by joseEnrique** [comment]
@CIECODE @pr3ssh Ya esta bien no? Imagino que como hubo un problema con las urls en el congreso, nosotros guardamos en Redis las urls que no debemos escrapear la siguiente vez, entonces se mantendría guardada y no se actualizaría con la correcta

**Comment by pr3ssh** [comment]
@joseEnrique Más bien el problema con las urls no era nuestro sino del enrutamiento de la web del Congreso ya que sin nosotros cambiar las nuestras en la bd de un dia para otro empezó a funcionar bien.
Lo que pasa aquí es diferente y es que tenemos una url para un acto que no corresponde (y eso puede estar pasando en otros actos).

**Comment by joseEnrique** [comment]
@pr3ssh pero si lleva a la iniciativa correcta, no?

**Comment by pr3ssh** [comment]
Ups! Magia!!!
