### ISSUE TITLE
¿Hay alguna forma, para nosotros, de saber el link al espacio-TIPI de un diputado aunque no haya realizado actos aún?

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#148]

**Comment by pr3ssh** [comment]
@CIECODE No, pero si te parece se puede preparar una página muy sencilla (solo para adminsitradores) con los enlaces alas páginas de cada uno de ellos.

**Comment by javipe** [comment]
Hola @pr3ssh , 
No es muy urgente. Lo usaríamos, por ejemplo, para dar la "bienvenida" a TIPI a diputados nuevos (como la diputada de C's) o para llamar la atención de algún diputado/a que después de unos meses no haya hablado aún de ningún tema TIPI.
Si lo que comentas es fácil, adelante. Algo lo usaremos seguro.
Javi

**Comment by pr3ssh** [comment]
Meanwhile... http://tipiciudadano.es/dips/58095ad4cc307270a3997757

**Comment by pr3ssh** [comment]
@CIECODE Te invito a hacer alguna búsqueda por Grupo Parlamentario o Diputado/a ;)
