### ISSUE TITLE
Duda a la hora de subir TIPI a Civicstack

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#151]
Hola @pr3ssh 
He ido a subir TIPI a la web de civicstack y me han entrado dudas al ver a lo que autorizas a la aplicación a hacer con tu cuenta de Twitter. Te hago un pantallazo, pero básicamente lo que me preocupa es que puedan escribir tweets en tu nombre y actualizar tu perfil. ¿Es esto normal? ¿No es excesivo? ¿Quizá subiéndolo a través de Github los requisitos sean menos bestias?
En cuando puedas, dime cosas.
![image](https://cloud.githubusercontent.com/assets/13982071/19718560/29c2ca28-9b66-11e6-96a5-976730894e6b.png)
Javi

**Comment by pr3ssh** [comment]
Twitter tiene solo una forma de integrar apicaciones y es ésta. Lo que quiere decir es que desde ahi podrias tu tuitear desde esa app. No creo que pase nada.

**Comment by javipe** [comment]
Ok. Pues al ataque.

Javi

**Comment by javipe** [comment]
Perdona, una cosa más:
Me pide que el logo lo suba a través de una Url... Perdona mi desconocimiento, pero ¿dónde tenemos el logo de TIPI de modo que lo podamos vincular con una URL (sin ser la home entera del proyecto?).

**Comment by pr3ssh** [comment]
http://tipiciudadano.es/images/logos-tipi/logo2_blanco.svg

y le seleccionas un color de fondo oscuro y ya.
