### ISSUE TITLE
Nuevo caso en el que el link del Congreso que proporcionamos lleva a un acto equivocado

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#152]
Hola @pr3ssh y @joseEnrique 

He dado con un nuevo caso en el que el link que proporcionamos al Congreso no lleva al acto parlamenatario correspondiente.

Se trata de: http://tipiciudadano.es/tipis/5806badecc3072a2a3216be9.

El acto trata sobre el IVA cultural y el link lleva a un acto sobre trabajadores domésticos.

El link correcto sería: http://www.congreso.es/portal/page/portal/Congreso/Congreso/Iniciativas?_piref73_2148295_73_1335437_1335437.next_page=/wc/servidorCGI&CMD=VERLST&BASE=IW12&PIECE=IWC2&FMT=INITXD1S.fmt&FORM1=INITXLUS.fmt&DOCS=1-1&QUERY=%28I%29.ACIN1.+%26+%28162%2F000188%29.

**Comment by javipe** [comment]
Hola @pr3ssh @joseEnrique 

No funciona ninguno, por lo que me temo que vuelve a no ser un problema nuestro, sino del Congreso.

¿Estáis 100% seguros de que la pelota está en su tejado? Porque si es así, creo que merece la pena que se lo comunique al Congreso para ver si hay alguna manera de evitarlo.

Abrazo.

Javi

**Comment by pr3ssh** [comment]
Creemos que el Congreso está cambiando las urls ya que nosotros no lo estamos haciendo y no tiene sentido que dejen de funcionar. Si se le puede hacer una pregunta de buenas a ellos sería genial.

**Comment by javipe** [comment]
Hola @pr3ssh 
Ya está enviado el correo a M.A. Gonzalo. Te he puesto en copia. A ver qué se cuenta.
