### ISSUE TITLE
¿Programamos un nuevo "escrapeo total" para este fin de semana?

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#153]
Hola @pr3ssh y @joseEnrique,

Desde Ciecode estamos a punto de acabar la revisión de los resultados y diccionarios de las 21 temáticas TIPI, por lo que sería el momento ideal para relanzar las arañas de nuevo sobre el total de la actividad parlamentaria.

Es un buen momento porque:
- Lo dicho, al haber revisado todos los diccionarios, muchos de los errores de inicio quedarían resueltos y mostraríamos ya de forma estable unos resultados más fiables.
- El lunes se puede decir que arranca la legislatura en todo su esplendor y así nos pilla limpios y aseados.
- Es previsible que la semana que viene tengamos alguna de las reuniones con los periódicos y así el nº de falsos positivos que ahora mostramos serían mucho menores...

¿Cómo lo veis? Si lo lanzáramos el sábado, por ejemplo, yo podría dedicarle un ratito el domingo para asegurar que no está fallando nada gordo o detectar cualquier cosa que pueda no estar funcionando bien.

Un abrazo.

Javi

**Comment by pr3ssh** [comment]
@CIECODE Me parece perfecto. Hay algunas tareas de revisión de ciertas expresiones que saltan y hacen que fallen los diccionarios. Me las intento apuntar aquí para esta tarde revisarlas.

**Comment by javipe** [comment]
Sí. Por favor. Yo me reservo tiempo entre hoy y mañana para acabar los 3 diccionarios que quedan y volver a echar un vistazo en diagonal para detectar alguna cosa que se nos haya podido pasar por alto.
Siguen guardándose espacios vacíos en algunos diccionarios a pesar de que nos obliga a borralos antes de poder cerrar y guardar cualquier modificación. Sospecho que ahí hay algo que nos puede estar generando problemas.
Abrazo.
Javi

**Comment by pr3ssh** [comment]
Hoy lo lanzamos.
