### ISSUE TITLE
¿Alguna forma de evitar que tras el nuevo 'escrapeo total' volvamos a mandar a los usuarios todas las notificaciones? 

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#154]
Hola @pr3ssh @joseEnrique 
De cara al nuevo 'escrapeo total' (por Dios, decidme cómo se dice correctamente cuando volvemos a lanzar las arañas de paseo) lo ideal sería que el sistema de alertas fuera capaz de discriminar y comunicar las novedades que ocurran desde ese día y no de nuevo todas desde el inicio de la legislatura, porque incluso nuestros más fieles seguidores se pueden desesperar.
¿Es posible?
Decidme cómo lo veis.
Un abrazo.
Javi

**Comment by pr3ssh** [comment]
@CIECODE Creo que lo mejor es que desactivemos el envio de correos antes de lanzarlo y luego lo volvamos a activar /cc @joseEnrique

**Comment by javipe** [comment]
Hola @pr3ssh y @joseEnrique 

Eso que propones, Pablo, suena bien. Si es tan fácil como suena es la solución perfecta. 

Lo ideal, de hecho, sería esperar a que hoy o mañana realizara el siguiente envío (lleva 3 días sin lanzar envíos) y desactivarlo ahí. Luego lo volvemos a activar el lunes para que notifique de las novedades a partir de ahí. 

Pero bueno, eso son detalles. Lo importante es que a los usuarios no les llegue una nueva notificación de centenas de actos y que tengamos que volver a mandar un mail explicativo.

Un abrazo.

Javi

**Comment by pr3ssh** [comment]
Lo de los no envios estos ultimos dias es porque no han habudo Tipis: http://tipiciudadano.es/escaner?dicts=&terms=&grupootro=&autor=&fechadesde=25%2F10%2F2016&fechahasta=28%2F10%2F2016&lugar=&ref=&vtipo=&tramitacion=&titulo=

**Comment by pr3ssh** [comment]
Lo otro, lo haremos así, para que despues del escrapeo no vuelva a lanzar un correo con 1000 iniciativas tipi.

**Comment by javipe** [comment]
Hola @pr3ssh, 

Creo que la comprobación que me has mandando (con la búsqueda limitada al periodo 25 a 28 de octubre) no nos vale, porque a día de hoy aún la fecha de los actos muestra la fecha de registro no la de última actualización, ¿no? Es decir, que podríamos haber etiquetado enmiendas o respuestas o aprobaciones en estos 3 últimos días de actos cuyo acto "madre" sea de antes del 25 y el buscador no las detectaría en esa búsqueda, ¿cierto?

En cualquier caso, cero preocupación. El buscador está funcionando bien y lo de las fechas ya lo tenemos hablado.

Abrazo.

Javi
