### ISSUE TITLE
Validar definitivamente la construccion de urls

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#161]
El formato es:

http://www.congreso.es/portal/page/portal/Congreso/Congreso/Iniciativas?_piref73_2148295_73_1335437_1335437.next_page=/wc/servidorCGI&CMD=VERLST&BASE=IW12&FMT=INITXDSS.fmt&DOCS=1-1&DOCORDER=FIFO&OPDEF=ADJ&QUERY=%28122%2F000001*.NDOC.%29

donde hay 3 variables que identifican la iniciativa: la legislatura, el tipo de expediente y el número asignado. Ambas 3 variables son constantes siempre en el tiempo para cada acto parlamentario

* La legislatura es la que va después de la instrucción IW
* El tipo de expediente es el que va después de QUERY=
* El número del expediente es el que va antes de .NDOC

**Comment by javipe** [comment]
Hola @pr3ssh 

¿Cuándo crees que podríamos implementar la construcción de los URLs permanentes? 

¿Crees que mientras tanto podríamos ejecutar de forma más frecuente (¿cada 24h al menos?) el escrapeo para reducir el tiempo en el que las URLs apuntan a actos equivocados?

Javi

**Comment by pr3ssh** [comment]
Hoy espero.

**Comment by javipe** [comment]
Genial
