### ISSUE TITLE
¿Hay forma de que no sea necesario escribir las tildes en los nombres de los diputados al usar el escáner?

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#163]
Hola @pr3ssh.

No es una cuestión urgente pero puede hacer que algún usuario no encuentre el diputado que está buscando.

Abrazo.

Javier

**Comment by javipe** [comment]
Hola @pr3ssh 
Este issue lo abrí para explicarle a los becarios cómo funcionaba esta plataforma. Lo cierro porque, aunque es cierto lo que te preguntaba, no es una cuestión muy relevante.
Abrazo.
Javi

**Comment by pr3ssh** [comment]
ack
