### ISSUE TITLE
Creemos que hemos detectado un error en el diseño de escrapeo de iniciativas

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#165]
Hola @pr3ssh 
Revisando los resultados de TIPI Lucas ha detectado una posible errata importante: si la separación entre actos es el nº de referencia, el título de la Comisión de un acto concreto lo interpreta como texto del acto anterior, por lo que si en el nombre de la Comisión aparece una palabra clave, lo estaría etiquetando erróneamente.
Aquí va la lista de Comisiones con nombre problemático que puedan generar el problema: 
- Comisión de cooperacion int. para el desarrollo: la expresión "cooperación internacional para el desarrollo" existe en TIPI.
- Comisión igualdad: el término "igualdad" no aparece solo en nuestros diccionarios, aunque sí acompañado de "apellidos" por lo que no es muy grave, aunque sí podría generar error si en el acto previo se dieran esos otros términos.  
- Comisión seg. vial y mov. sost: "movilidad sostenible" es un término TIPI.
- Comisión estudio cambio climático:  la expresión "cambio climático" existe en TIPI. 
- Comisión derechos de la infancia y adolescencia: el término "derechos de la infancia" existe en TIPI. 
- Comisión para las políticas integrales de la discapacidad: "discapacidad" no aparece sola en nuestros diccionarios, aunque sí acompañado de "apellidos" por lo que no es muy grave, aunque sí podría generar error si en el acto previo se dieran esos otros términos.   
- Comisión para calidad democrática contra corrupción: el término "corrupción" no existe sólo, aunque sí junto a otros (empresa multinacional, Convención de Naciones Unidas Contra...) por lo que no es muy grave, aunque sí puede generar error si en el acto previo se dieran esos otros términos.

Abrazos,
Javi

**Comment by javipe** [comment]
Hola @pr3ssh:
Te paso dos casos concretos en los que ocurre el error que te comentaba ayer (de confundir el nombre de la Comisión del acto siguiente como texto del acto anterior):
- Caso en la Comisión de políticas integrales de la discapacidad: 161/000817. La palabra "discapacidad" del nombre de la Comisión se asocia con "empleo" del texto del acto anterior y genera un match erróneo.
- Caso en la Comisión de Empleo y Seguridad Social: 161/000791. Ocurre exactamente lo contrario. El nombre de la Comisión incluye "empleo" y el texto del acto anterior contiene la palabra "discapacidad".

**Comment by pr3ssh** [comment]
@joseEnrique Pudes echar un cable con esto?

**Comment by javipe** [comment]
Hola @joseEnrique y @pr3ssh,

He estado revisando casos concretos en los que se estén dando dichos errores. Parece que todos los casos que tenemos detectados son de un único tipo de iniciativas, las 161/xxxxx que se corresponden a PNL en Comisión.

Ahí os pongo algún ejemplo para que podáis verlo directamente y valorar la situación:
- 161/000705: La siguiente iniciativa a la nombrada es de la Comisión de derechos de la infancia y adolescencia. Por lo tanto saltan "adolescencia""infancia""Derechos de la infancia".
- 161/000884: La iniciativa tiene 4 etiquetas en infancia. Todas ellas erróneas, debido al nombre de la comisión de la siguiente iniciativa.

Un abrazo,

Javi

**Comment by pr3ssh** [comment]
@joseEnrique ?
