### ISSUE TITLE
Reubicar la info sobre el "Estado de tramitación" en la maquetación de las fichas TIPI

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#169]
Hola @pr3ssh,

Incorporo esta mejora, que nos indicó Miguel Ángel Gonzalo y te la asigno y ya veremos en qué momento la implementamos, pero para que no se quede en el olvido. ¿Ok?

Un abrazo.

Javi

**Comment by javipe** [comment]
Hola @pr3ssh 
Reabro este issue para que decidamos si dejamos el estado de tramitación tal y como está en la maquetación actual o si implementamos el cambio sobre el que hablamos en algún momento de poner la "expresión bonita" más destacada (debajo del logo del Parlamento que da acceso a la web del Congreso, por ejemplo).
Lo paso al Milestone para, como en el resto de asuntos, que decidamos ahora qué hacer con ello.
Javi

**Comment by pr3ssh** [comment]
ack
