### ISSUE TITLE
Al editar diccionarios desde Admin hay que borrar muchos campos vacíos antes de que te deje guardar (muy engorroso)

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#171]

**Comment by javipe** [comment]
A este mismo tema se refiere el issue #155 en el que viene explicado el problema (por si lo queréis consultar allí).
Javi

**Comment by pr3ssh** [comment]
Agrego la #155 al Milestone!

**Comment by javipe** [comment]
Hola @pr3ssh Sigue habiendo huecos vacíos donde se han eliminado términos. Si no ves factible solucionarlo ahora lo pasamos al Milestone v2.3

**Comment by pr3ssh** [comment]
@CIECODE Eso ahora mismo en el sistema no produce ningún fallo porque está controlado pero aun así hay que solucionarlo sí. Lo que vamos a hacer es diferenciar entre

1. Dejar el sistema estable en contenido
2. Administrar de forma eficiente los términos de los diccionarios

La 1. la resuelvo ahora. La 2. tiene que ver con un Sw de gestión que os voy a instalar en vuestros equipos.

**Comment by pr3ssh** [comment]
@CIECODE Ya están quitados los huecos vacíos de los términos de los diccionarios. Hasta que no os instalemos el Sw no editéis más téminos desde el ADMIN.
