### ISSUE TITLE
Nuestro estado de tramitación "Respondida" no da ningún resultado, cuando ya hay más de 50 preguntas respondidas

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#173]
Hola @pr3ssh 

Ahora mismo, si tú filtras por "Estado de Tramitación: Respondida", el buscador te dice que no hay resultados.

Sabemos que eso no es verdad, dado que si flitras por "Pregunta oral y su respuesta" y pones como autor el Gobierno, te aparecen 47 iniciativas, que obviamente son respuestas.

Este es un ejemplo concreto por si quieres ver uno: http://tipiciudadano.es/tipis/58549202cc30722f229e6cf3

Lo que he observado es que el estado de tramitación que mostramos (y, por tanto, el que usa el Congreso para estas situaciones) es: "Tramitado por completo sin req. acuerdo o decisión", cuando en realidad, a efectos de TIPI esto significa "Respondido". Aún no he encontrado ninguna "Pregunta al Gobierno con respuesta escrita" por lo que no he podido ver cómo llama el Congreso a cuando éstas han sido respondidas, pero probablemente sea lo mismo (lo miro y te lo digo).

Este problema forma parte del problema más amplio que nos señaló en su momento Miguel Ángel Gonzalo (que había palabrejos internos del Congreso y que él nos podía ayudar a traducirlos a términos más entendibles). 

En este caso el problema es mayor, dado que este palabrejo está provocando que demos la info incorrecta (como si no hubiera preguntas respondidas!!!).

¿Crees que en concreto con este error podríamos hacer que TIPI entienda que cuando pone "Tramitado por completo sin req. acuerdo o decisión" quiere decir "Respondida"?

Abrazo,

Javi

**Comment by pr3ssh** [comment]
Si te parece podemos hacer eso, que crea que respondida significa ese palabrejo (y esperemos que no lo pongan de otra forma).

**Comment by javipe** [comment]
Hola Pablo.

Me parece bien.

Una de las cosas que quiero hacer estos días de vacaciones es sacar todos los palabrejos que detectamos en TIPI tratar de adivinar qué significan y presentárselo a Miguel Ángel Gonzalo para que nos dé el visto bueno o nos sugiera él alguna idea mejor.

Javi
