### ISSUE TITLE
Un nuevo tipo de error en el escrapeo que genera error en el etiquetado (pequeño y suponemos que fácil de solucionar)

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#174]
Hola @pr3ssh.

Te pasamos un nuevo tipo de errata en el escrapeo. Te la describimos y te ponemos dos ejemplos:

Con el término "reo" (que tenemos en el diccionario escrito de la siguiente forma "\breo\b") Tipi reconoce la palabra "aéreo" erróneamente. Suponemos, que se debe a que Tipi no reconoce como letra las que van con tilde y lo identifica como un símbolo, por lo que el \b no impide que salte. Lo mismo sucede con "SOVI" y "Unión Soviética".

Ambos se dan en el mismo acto parlamentario: 161/000908.

Abrazo.

Javi

**Comment by pr3ssh** [comment]
Exacto! Eso ocurre por el carácter con tilde que no es como PCRE reconoce que sería a-z o A-Z.
Recomiendo editar el diccionario en tal caso para contemplar ese escenario y en tal caso para esa iniciativa editar los términos que hayan saltado para eliminarlos (ya se puede desde la semana pasada).

**Comment by javipe** [comment]
@pr3ssh Cuál es la solución que propones en el comentario anterior? Hemos visto que reo ya no existe como término y que "SOVI" sigue detectando "Unión Soviética.

**Comment by pr3ssh** [comment]
Para SOVI:

`\b[^áéíóúñ]sovi[^áéíóúñ]\b`

Se puede probar en https://regex101.com con la frase *La Unión soviética es un sovi en toda regla*
