### ISSUE TITLE
Distinguir en el escáner las iniciativas 'aprobadas' de las 'respondidas' (ahora mismo son lo mismo)

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#179]
Hola @pr3ssh 
Esta es la 2ª mejora necesaria tras la implementación del criterio 'estado de tramitación' en el escáner: ser capaces de distinguir entre las iniciativas respondidas y las aprobadas, que ahora mismo están dentro del mismo saco (aprobadas).

Lo bueno es que sólo hay 4 tipos de actos TIPI (creo que no se me ha escapado ninguno) en los que el estado puede ser 'respondida'
- Interpelación urgente (171/000025).
- Pregunta oral en Pleno (180/000000).
- Pregunta oral al Gobierno en Comisión (181/000000).
- Pregunta al Gobierno con respuesta escrita (184/000000).

Es 'respondido' cuando en estos 4 tipos de actos el Congreso dice 'Tramitado por completo sin req. acuerdo o decisión'.

Esta info la tienes en el Drive donde tenemos registrada toda el análisis sobre el estado de tramitación.
Si tienes cualquier duda, dime.
Abrazo.
Javi

**Comment by pr3ssh** [comment]
* Si se busca solo por RESPONDIDA te salen aquellas iniciativas que pueden ser respondidas.
* Si se busca por RESPONDIDA y un tipo de acto, la búsqueda es normal.

Hacer lo mismo con las CELEBRADAS.
