### ISSUE TITLE
Corregir las tildes de los CSV

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#180]

**Comment by spolpen** [comment]
@CIECODE Hemos realizado diversas pruebas y nos aparecen correctamente las tildes, además de reconocer 'UTF-8' como formato en el que se descargan los datos.

¿Puedes confirmar si está solucionado?

**Comment by spolpen** [comment]
@CIECODE ¿Has podido realizar una nueva prueba de descarga en CSV? Por confirmar que funciona correctamente y cerrar la tarea.

**Comment by javipe** [comment]
Hola @pr3ssh 
Con las descargas del CSV nos pasa lo mismo que nos pasaba con la descarga de diccionarios antes de que nos lo empezarais a pasar vosotros en el formato csv ese molón, que podemos ver bien. Ahora mismo lo vemos con todas las vocales tildadas en formato imagen y con algunas otras letras (ñ si mal no recuerdo) también raro.
Lo vuelvo a abrir.

**Comment by pr3ssh** [comment]
@CIECODE Probad a poner en el mecanismo de importación la codificación UTF-8 de LibreOffice o Microsoft Excel. Decidme si os funciona.

**Comment by javipe** [comment]
Hola @pr3ssh 
Lo he abierto en el formato UTF8 y lo visualizo bien pero luego no he conseguido descargarlo en ese formato para que se me quede de forma correcta en el csv o en excel...
Lo voy a seguir intentando o pidiendo ayuda aquí.

**Comment by pr3ssh** [comment]
@CIECODE El fichero se genera con codificación UTF-8 y por eso se requiere al abrirlo (a mi siempre se me muestra por defecto en la app de LibreOffice).

**Comment by javipe** [comment]
Yo creo que no estoy haciendo bien lo de la conversión... (pero ahora no tengo a quién preguntarle por aquí).
Aún así, si yo soy más o menos el usuario medio (por tecnología que uso y conocimientos que tengo) la solución actual no es aún satisfactoria, porque yo no consigo verlo sin los caracteres raros.

**Comment by javipe** [comment]
Si lo abro desde el editor de texto (Text Edit) la descarga se ve bien. El error da cuando se abre con el excel y no sé cómo forzar a que excel abra en otro lenguaje del que abre por defecto

**Comment by pr3ssh** [comment]
@CIECODE Entendido! Dejame y lo reviso de nuevo. Si no, mañana hacemos unas pruebas en la reunión compartiendo pantalla.

**Comment by pr3ssh** [comment]
Esto es un problema más de formas de importación en Excel que de tildes ya que al estar en UTF-8 las tildes aparecen bien. Solo se necesita seleccionar correctamente la codificación de caracteres.
