### ISSUE TITLE
Permitir descarga de datos en XSL

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#181]

**Comment by javipe** [comment]
Hola @pr3ssh si te parece, reabrimos este issue y decidimos si lo pasamos al Milestone V2.3 (o algo similar), para que no se nos quede aquí olvidado.

**Comment by pr3ssh** [comment]
@CIECODE Claro! Pero es que estaba algo repetida con la #202. Yo la cerraría y dejaría la otra (que está además ya en el Milestone 2.3).
