### ISSUE TITLE
Error de diseño de escrapeo: tipo de acto (180/xxx y 181/xxx): evitar que escrapee los Diarios de Sesiones

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#196]
Hola @pr3ssh 
Hemos visto que en las preguntas orales (en Pleno o Comisión), las arañas escrapean también el Diario de Sesiones (en el que están las respuestas del Gobierno, junto a otros actos como Comparencias) y, como sabes, no somos capaces de distinguir entre el texto de los distintos actos.

Por lo cual, optamos para los actos 180 y 181 por la misma solución que con las Comparecencias: limitarnos a escrapear el título de las iniciativas (manteniendo eso sí, la distinción entre estado de tramitación "Pregunta" y "Respuesta" tal y como está.

Si te parece, y como es una cuestión no muy complicada, lo metemos en el Milestone actual (V.2.2). Si no, re-etiquétalo tú como V2.3.

Abrazo.

Javi

**Comment by pr3ssh** [comment]
@CIECODE  Lo dejamos en éste y ya ajustamos horas. No te preocupes.
