### ISSUE TITLE
Mostrar en una caja informativa qué es lo que se está buscando en ese momento en el buscador

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#38]

**Comment by pr3ssh** [comment]
@CIECODE Esta creo que no es necesaria. O tendríamos que ver dónde meterla si se ve que aporta.

**Comment by pr3ssh** [comment]
@CIECODE Está hecha porque era sencilla. La subimos? He puesto un máx de 150 chars antes de que se corte.

**Comment by CIECODE** [comment]
Súbela!!!
