### ISSUE TITLE
Redactar indicaciones de cómo o qué buscar (tips del buscador)

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#44]

**Comment by pr3ssh** [comment]
Una vez redactadas las pasamos a la web.

**Comment by javipe** [comment]
Hola @pr3ssh ahí va mi nuevo intento de TIPI-tips cortas y afiladas!!!! Te paso 6 por ahora, para no atascarme y en estos días le doy otra pensada y te mando alguna más, ¿ok?
1. Tip#1: Una vez hayas escogido un tema, se desplegarán todos sus términos asociados.
2. Tip#2: Los nombres de l@s diputad@s se auto-completan. Introduce una letra y verás.
3. Tip#3: La "referencia" es como el DNI de los actos parlamentarios: es un número único que los identifica.
4. Tip#4: Escoge un autor de entre los siete Grupos Parlamentarios y el Gobierno.
5. Tip#5: Escoge de entre los 13 tipos de actos parlamentarios a los que TIPI da seguimiento.
6. Tip#6: Si has encontrado la información que buscabas no olvides que puedes descargártela gratis.

**Comment by javipe** [comment]
La 7ª sería: Si al acceder a la web del Congreso de los Diputados desde TIPI no se carga la página, se soluciona si refrescas el buscador".
