### ISSUE TITLE
Permitir seleccionar más de un tipo de iniciativa en el buscador

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#5]

**Comment by pr3ssh** [comment]
@CIECODE Funcionalmente no puede ser muy usable. ¿Queréis tirar de todas formas por ahí?

**Comment by pr3ssh** [comment]
@CIECODE Qué pensais sobre esto? Lo veo poco usable cuando habrá muchos tipos de iniciativas.

**Comment by pr3ssh** [comment]
Se elimina de esta versión.

**Comment by javipe** [comment]
Estoy 100% de acuerdo en el caso de los tipos de iniciativas, pero sí lo veo útil en el caso de: temas y autor, por ejemplo. ¿Está previsto?

**Comment by pr3ssh** [comment]
Ciertamente no estaba planificado ni contemplado. Crea si te parece la tarea pero es algo que habría que hablarlo bien porque cambiaría la interfaz del buscador completamente (no tanto para el autor pero si para la tematica.

**Comment by javipe** [comment]
Hola, 
Pensándolo bien, desde el punto del vista del usuario no hay TANTAS ventajas de poder hacer una búsqueda múltiple de autor o tema (puede hacer dos búsquedas consecutivas y listo).
Donde sí creo que hay un valor añadido grande es en poder escoger varios términos en una búsqueda dentro de un determinado ámbito. Si veis que esto ahora es inabarcable, se deja aparcado, pero creo que es algo que en un futuro TIPI va a tener que incorporar, porque para un usuario medio, optar por un único término de interés dentro de una lista de 100 términos va a ser complicado (máxime cuando muchos de ellos se parecen mucho y sólo son dos términos distintos por necesidades gramaticales, no por tener sentidos distintos. Por ej. "viejo Vs anciano".).
Si te parece: a) olvidamos el tema de autor y ámbito temático; 2) dime si merece la pena crear un issue relacionado con la selección de varios términos en una búsqueda.
Abrazo.
Javi

**Comment by pr3ssh** [comment]
Ok! Ya hablaremos sobre cómo resolver el diseño de la interfaz porque tal y como está ahora no es seleccionable máß de uno ya que es una lista de selección única; pero lo que comentas me parece lógico. Abro ésa y cierro ésta por no confundir y ya veremos cuándo podemos acometerlo.
