### ISSUE TITLE
Mostrar puntos suspensivos si las celdas de las busquedas son demasiado laaargas

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#59]

**Comment by pr3ssh** [comment]
@CIECODE Vemos esta tarea como necesaria? La tengo casi hecha vamos pero quería validarlo.

**Comment by pr3ssh** [comment]
@CIECODE Está hecha porque era sencilla. La subimos? He puesto un máx de 150 chars antes de que se corte (no era la #38 sino ésta)

**Comment by javipe** [comment]
Yo creo que sí. Adelante!

**Comment by javipe** [comment]
Hola @pr3ssh,

Dicen que rectificar es de sabios... Ahora que lo he visto implementado, me he dado cuenta de que acortar los títulos no aporta mucho. Por dos razones:
1. Los primeros términos son casi siempre cuestiones genéricas "Solicitud de comparecencia al Secretario de Estado..." y cuando van a empezar con la chicha, se corta.
2. El listado de temas activados suele ser más largo, por lo que no acorta el largo del acto en el buscador.
Siento haberte hecho perder el tiempo, pero creo que está mejor como estaba antes...
Un abrazo.
Javi

**Comment by pr3ssh** [comment]
Hecho!
