### ISSUE TITLE
Sustituir \b y \W por \\b y \\W

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#62]
Me pongo con ello @pr3ssh

**Comment by javipe** [comment]
Una duda @pr3ssh 
¿Tengo que cambiar el \b y el \W sólo cuando comience así la expresión regular o en todos los casos?

**Comment by pr3ssh** [comment]
@CIECODE en todos los casos

**Comment by javipe** [comment]
@pr3ssh Gracias!
