### ISSUE TITLE
Un par de preguntas previas de Luis Cacho para Enreda

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#63]
Hola @pr3ssh Acabo de hablar con Luis Cacho y se va a poner en breve (ya a principios de la semana que viene, supongo). Y me ha preguntado un par de cosas:
- ¿Qué numero de visitas estimamos al día en la página? Yo no sabría decir. Me ha preguntado que si 1000... yo creo que ni de coña. ¿No?
- ¿Tamaño de la base de datos?
- ¿Cuánta RAM estimáis que será necesaria (para bbdd y servidor web)?
  No hay prisa, pero cuando nos podáis decir algo, genial.
  Javi

**Comment by pr3ssh** [comment]
@CIECODE Respondo a las preguntas:
- Ahora mismo son muy pocas y creo que en las épocas más fuertes el número de visitas no superaba las 100 al día. Pero eso va a cambiar según nuestra previsión. Podríá rondar en torno a las 500 diarias como mucho (suposiciones).
- Actualmente la BD con todos los datos de la Xlegislatura ocupa 2,3 Gb con los datos e índices de las colecciones. No creo que en total supere para esta XII legislatura los 3Gb en total y puede ser una buena cantidad para no quedarnos cortos.
- Esta pregunta siempre es complicada. Tanto el escrapeo como la aplicación consumen bastante or lo que mi pregunta iría más sobre.. cunánta RAM nos podemos permitir?

**Comment by javipe** [comment]
@pr3ssh Me dice Luis que si con 6GB de RAM tendríamos suficiente? Por lo que parece, habitualmente habrá más disponible. El problema podría surgir si coincide con algún pico de uso de los servidores por alguno de los proyectos gordos que maneja la empresa... ¿Cómo lo veis? Lo ideal sería tirar con la capacidad que nos pueda ofrecer la empresa, pero si es estrictamente necesario, podríamos valorar el invertir en ello.
Abrazo.

**Comment by pr3ssh** [comment]
Actualmente tenemos 4Gb por lo que creo que para dar un servicio en
condiciones con 6Gb iríamos bastante bien.

Pablo Martín Muñoz
Hacker Cívico
