### ISSUE TITLE
Permitir seleccionar más de un témino de una temática en el buscador

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#65]

**Comment by pr3ssh** [comment]
@CIECODE Esto es algo que se puede asumir pero que habría que ver cómo se hace ya que solo las haría sobre un mismo diccionario y ver si el buscador actual lo permite y cómo quedaría el elemento de interfaz.

**Comment by javipe** [comment]
Hola, 
De todos los asuntos pendientes creo que este es de los más estratégicos, porque todos los diccionarios están diseñados con términos muy específicos que en muchos casos son insuficientes para responder a una búsqueda ("abandono._tercera edad" y "abandono._viej[oa]s" o "abandono.*ancian[oa]"... No tendría sentido tener que hacer tres búsquedas si lo que te interesa es el abandono de los agüelicos...

En el buscador de la versión móvil, ya hay algo similar a lo que podría ser la solución gráfica: salen unos circulitos que se activan cuando escoges una opción.

Lo hablamos.

Javi

**Comment by pr3ssh** [comment]
Implementar una interfaz modal que te permita seleccionar mas de un termino dado un diccionario seleccionado.
Una vez se seleccionen que te ponga algo asi como "termino 1, termino 2 y 3 mas (ver terminos)"

Importante que la busqueda de los terminos la haga con el operados OR.

**Comment by javipe** [comment]
Hola @pr3ssh,
Te voy a ir poniendo por aquí los errores que hemos ido detectando Lucas y yo del nuevo desarrollo del buscador de TIPI. ¿Ok?

**Comment by javipe** [comment]
Ahí van. El resumen es: "las temáticas en los que los diccionarios aparecen, están funcionando bastante bien".

Las principales erratas que hemos ido detectando son:
1. En estos momentos sólo se despliegan los diccionarios de 3 o 4 temáticas, el resto sale el símbolo de Stop.

2. Cuando escoges una temática se queda "enganchado" en ese diccionario y aunque busques en otra temática te sigue mostrando ese diccionario.

3. La "búsqueda de términos" es sensible a las mayúsculas y minúsculas. Lo ideal es que no lo fuera, porque si la gente no sabe que hemos escrito la primera palabra con mayúscula, lo escribe con minúscula y no le salta ningún resultado, cuando sí están, pero en mayúscula. ¿Es posible hacer el buscador no-sensible?

4. El buscador ahora muestra los criterios bajo los que estás realizando la búsqueda, en todos los campos, menos en los términos escogidos. No sé si habías pensado en alguna solución para esto, aunque no se fuera a implementar ahora mismo. Recuerdo que hablamos de que se quedaran los términos escogidos dentro de un cuadro de texto o algo así.

Por ahora eso es todo. Voy a comprobar más en profundidad los resultados que arroja, por si hubiera algún comentario en ese sentido.

Abrazo.

Javi
