### ISSUE TITLE
En algunos diputados su "página propia" no funciona

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#74]

**Comment by pr3ssh** [comment]
@ciecode puedes pasarme algun ejemplo?

**Comment by javipe** [comment]
Hola @pr3ssh 
Fue anoche haciendo algunas pruebas, pero hoy me ha funcionado bien siempre. Seguiré atento por si acaso, pero si quieres podemos cerrar el issue y se reabre si se vuelve a dar el caso.
