### ISSUE TITLE
Las "metabúsquedas" desde los términos no están funcionando

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#76]

**Comment by pr3ssh** [comment]
@CIECODE no entiendo esto.

**Comment by javipe** [comment]
Perdón @pr3ssh , que no vi esta respuesta tuya.
Cuando llegas al espacio de un acto parlamentario y dice, por ejemplo, "Sanidad por mencionar: Salud sexual y reproductiva, Hepatitis C y Copago", ayer si clickabas en Copago iba a una página donde estaban todas las iniciativas en las que se había usado el término Copago. Eso duante el día hoy no ha funcionado y salía un "Error 404". Ahora lo he vuelto a probar y sí funciona...
¿Le habéis metido mano?
Javi

**Comment by pr3ssh** [comment]
Si. Mil perdones por eso. Fue porque cambiamos a última hora buscar por escáner y se quedó un enlace roto y salió el error 404 de página no encontrada.
