### ISSUE TITLE
Al darle a descargar la info de una búsqueda, el archivo que descarga está vacío

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#77]

**Comment by joseEnrique** [comment]
@pr3ssh te refieres al csv?

**Comment by javipe** [comment]
Hola @joseEnrique sí, la descarga del csv genera un archivo vacío. 
Javi

**Comment by joseEnrique** [comment]
@CIECODE ayer mientras se presentaba lo arreglé

**Comment by pr3ssh** [comment]
Hecha! Gracias @joseEnrique. La cierro.
