### ISSUE TITLE
El texto de la home para que la gente se dé de alta repite muchas veces la misma frase

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#79]

**Comment by pr3ssh** [comment]
@CIECODE Puedes proporcionarme un texto que **nos represente**? ;)

**Comment by javipe** [comment]
Hola @pr3ssh.
El texto actual dice: 
"Las alertas al instante
Un sistema de alertas potente y configurable
Entérate de toda la información parlamentaria sobre pobreza y exclusión social".

Sugiero que diga:
"Personaliza tu sistema de alertas de TIPI y mantente al día.
Las novedades del Congreso de los Diputados en tu correo electrónico.
Date de alta en nuestro Sistema Personalizado de Alertas y mantente informado de cualquier novedad que ocurra en el Congreso de los Diputados sobre tus temas de interés. ¡¡¡Es fácil, práctico y gratis!!!"

¿Qué te parece?

**Comment by pr3ssh** [comment]
Me parece perfecto! He hecho un pequeño recorte del titulo pero lo demás está ok!
