### ISSUE TITLE
El eje del gráfico de la home no muestra % sino números totales. Hay que cambiar ese 600 por un "100%" y así sucesivamente

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#80]

**Comment by pr3ssh** [comment]
@CIECODE Tengo mis dudas al respecto. Me gusta que se mida por números absolutos para que se vean las cantidades que manejamos y que luego el resultado sea un porcentaje.

**Comment by javipe** [comment]
Hola, 
En relación con este gráfico hay un par de problemas previos. Si te parece, cierro este issue y creo uno más general sobre esta visualización y cuando decidamos las tareas que se desprenden de esto, creamos issues específicos.
Javi
