### ISSUE TITLE
Verificar el estado de tramitacion en las busquedas

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#81]

**Comment by joseEnrique** [comment]
@pr3ssh a que te refieres con esto? A como sale la tramitación? Se coge integramente de la web

**Comment by pr3ssh** [comment]
@joseEnrique No. A que pongamos en el selector del buscador todas los posibles valores de ese campo.

**Comment by joseEnrique** [comment]
@pr3ssh es problema es que no hay un numero fijo de tramitacion, puede salir Comision de arte en 23/12/15

**Comment by pr3ssh** [comment]
@joseEnrique  Pero el estado de tramitacion es un conjunto vacio no? Aprobada, con modificaciones, rechazada, etc. no?

**Comment by joseEnrique** [comment]
@pr3ssh Se coge de tramitacion de los metadatos y estos no son homogéneos

**Comment by pr3ssh** [comment]
@joseEnrique Podemos sacar un listado de cuales son las más homogéneas? Lo que son estados propiamente dichos vamos.

**Comment by joseEnrique** [comment]
@pr3ssh el problema es que vienen con fechas y demas, pero puedo hacer fuzzy de una lista que se ponga la tramitación que más se le parezca

**Comment by pr3ssh** [comment]
@CIECODE Esto es algo confuso porque los valores son dispares. Crees que podemos sacar un listado de cosas que pueden aparecer en el estado de tramitacion y luego hacer una busqueda en base a ellas? Algo del tipo: aprobada, rechazada / aunque luego en el txto del estado de tramitacion ponga "aprobada por el XXX con fecha YYY" o "rechazada por el pleno"

**Comment by javipe** [comment]
Hola @pr3ssh y @joseEnrique 
Sí, puedo hacer un poco de investigación al respecto y a ver qué se nos ocurre.
La situación actual es muy confusa porque, por ejemplo, en este acto (http://tipiciudadano.es/tipis/57eae656cc3072a4f10439f9) damos como Estado de tramitación "Concluido/Rechazado" pero si buscas a través del escáner iniciativas rechazadas te dice que no hay ningún resultado.
Abrazo.
Javi
