### ISSUE TITLE
Crear bots que generen tweets automáticos

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#83]

**Comment by pr3ssh** [comment]
@spolpen Se podría hacer uso de las alertas que se van generando día a día y así rescatar textos para los tuits. Monta primero el esqueleto básico del sistema y luego ya vemos con @CIECODE el contenido. Recuerda, en Python ;)

**Comment by spolpen** [comment]
@CIECODE ¿Podéis crear una app de Twitter desde @tipi_ciudadano y enviarnos por email los siguientes datos para configurar el bot?
 
- Consumer Key (API Key)
- Consumer Secret (API Secret)
- Access Token
- Access Token Secret
