### ISSUE TITLE
Hacer resumen del nombre de los diccionarios para que quede bien la visualización

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#84]

**Comment by javipe** [comment]
Hola @pr3ssh ¿hay un número máximo de caracteres? Dame alguna indicación de cuáles son las restricciones y te lo paso esta misma tarde.

Javi

**Comment by pr3ssh** [comment]
8 o quizás 10? O es muy poco. Tambien se puede poner ese area algo mas grande para que quepa algo con 12 caracteres pero si es una palabra mejor que mejor.

**Comment by javipe** [comment]
Pues allá va, @pr3ssh. No es la situación ideal, porque hay algunas que no tienen fácil abreviatura (Protección Social) y otras, que su nomenclartura tiene connotaciones y hay que ir con ciudado (Igualdad de Género; Personas con Discapacidad...), pero si tiene que ser, ahí van las versiones cortas:
- Dependencia
- Infancia
- Cambio Climático (o, en su defecto: C. Climático, más no se puede abreviar).
- Vivienda
- Sanidad
- Empleo
- Sinhogarismo (o, si no pudiera ser: Sin hogar).
- Educación
- Comercio
- Cooperación
- Transparencia
- Adicciones
- Mayores
- Reclusos
- Migraciones
- Pob. gitana (si no puede ser, pon: Gitanos).
- Conflictos.
- Género.
- Protección Social (esto no se puede abreviar, como mucho, poner: "Protecc. Soc" pero queda regular.

Abrazo,

Javi

**Comment by pr3ssh** [comment]
@CIECODE Gracias Javi. Faltan dos por casualidad?

**Comment by pr3ssh** [comment]
Resuelto. Eran discapacidad y fiscalidad.

**Comment by javipe** [comment]
Ups, no. Ha sido sin querer... A ver si sé cuáles faltan...
- Fiscalidad.
- Discapacidad

**Comment by javipe** [comment]
Te adelantaste!!!
