### ISSUE TITLE
Lo ideal sería que si llegas a "Dependencia" y clickas en uno de los diputados más activos, la búsqueda a la que te lleve sea la de ese diputado en ese tema y no a la actividad de ese diputado en general

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#85]

**Comment by pr3ssh** [comment]
@CIECODE Creí que era interesante que desde una página deresumen fueras a otra página de resumen que son las que se compartirán más. Si te parece lo hablamos porque es importante.

**Comment by javipe** [comment]
Sí, puede que tengas razón. Dejémoslo aparcado por ahora y lo consultamos con terceros usuarios a ver cómo lo ven. ¿Ok?

**Comment by pr3ssh** [comment]
Ok
