### ISSUE TITLE
Mantener seleccionado el diccionario y el término que está activo en la búsqueda

### ISSUE THREAD

**Issue by pr3ssh** [CIECODE-Madrid/tipi#86]

**Comment by javipe** [comment]
Hola @pr3ssh 
¿Cómo va esta tarea? Creo que nos resultaría muy útil para enlazar desde la home o por redes sociales, porque ahora se ve la carcasa del escáner y los resultados, pero no cuáles son los criterios de búsqueda que han generado estos resultados.
Abrazo.
Javi
