### ISSUE TITLE
Revisión de la visualización principal de la home

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#87]
Hola @pr3ssh 
Como hasta ayer no pudimos ver el gráfico de la home en funcionamiento hay un par de comentarios importantes que os quiero hacer al respecto. Como comentaba al cerrar el issue anterior sobre esto, una vez que decidamos las tareas específicas, creamos issues más concretos que este general.
Ahí van mis comentarios:
- Sea cual sea el resultado de la revisión de la visualización hace falta ponerle un título encima. Ya sea un "Los temas de los que más se habla en el Congreso son..." o lo que sea. Decidámoslo una vez hayamos cerrado el resto de cuestiones.
- Hay un problema con los % que estamos mostrando ahora. Muestran el peso que tiene cada uno de los temas... en comparación con los temas TIPI. Es decir, estamos diciendo que Infancia representa un 25%, no del total de debate político en España... sino de un total creado artificialmente por nosotros. Aquí sólo veo dos opciones: 1) que ese % lo calculemos del total de "actos del Congreso" y no de "actos TIPI" (bastaría con guardar la cifra total y calcular: % de infancia = (total actos infancia/ total actos Congreso); 2) no mostrar porcentaje y sólo mostrar magnitudes: infancia va la primera de los temas TIPI porque lleva 235 actos; en segundo lugar va..., etc.
- Si ese "600" va a mostrar el total de actos TIPI acumulados hasta ese momento (o en el periodo temporal X, si acometemos ese enhancement), habría que decirlo. Es decir, hay que explicar a qué responden las magnitudes de la visualización. Bastaría con poner encima un "Total actos TIPI".

En función de qué me digas, creamos issues específicos para repartir roles y asignar tareas.

Javi

**Comment by pr3ssh** [comment]
@CIECODE Creo que está todo ya resuelto con los ultimos cambios de ayer. Los ticks de las barras hacen indicar que es sobre un total que ahora es el de actos del Conrgeso.

**Comment by javipe** [comment]
@pr3ssh Sí, creo que sí. Sólo se me ocurren dos mínimas mejoras:
1. En algún sitio (quizá debajo de la tabla, antes de donde ahora ponemos lo de "Estadísticas extraídas de nuestra base de datos...") habría que añadir un "Los % muestran el peso de cada temática en el conjunto de la actividad del Congreso de los Diputados". 
2. La tabla de las estadísticas de las 21 temáticas mola un huevo!!! Habría que hacer algo para que estuviera más visible. ¿Se podía poner "en este enlace" en amarillo TIPI?

**Comment by javipe** [comment]
Hola @pr3ssh , 
Hay dos cosas más sobre la visualización de la home, una más importante que otra.
- La importante: sería muy útil si el nombre de los 5 temas de la visualización estuviera "activo" y vinculado con la página temática correspondiente.
- La menos importante: ¿sería posible (y visualmente atractivo) poner el nº total de actos sobre el que se calculan los porcentajes de cada tema (es decir, ahora el 2000 y pico) a la derecha del gráfico?

**Comment by pr3ssh** [comment]
- Los temas ya los he vinculado con sus páginas y queda mucho más completo.
- Lo del total se puede meter por ahí pero no lo veo tan relevante, teniendo en cuenta que se supone los márgenes que se trabajan.
- Cambiado los enlaces a la página de estadísticas y los textos.

**Comment by javipe** [comment]
Genial, 
Sólo hace falta corregir una errata que se ha colado: "stadísticas" por "estadísticas".
Gracias,
Javi
