### ISSUE TITLE
Que el "share" de Twitter desde la página-TIPI de un diputado muestre el tuit del diputado

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#89]
Hola @pr3ssh.
Sería muy conveniente que el mensaje automático que se genera al darle a share en Twitter desde el espacio específico de un diputado muestre el tuit de dicho diputado.
Con sólo esa mejora, generamos una notificación en el twitter del diputado, aumentando mucho así la posibilidad de que nos conozca, retuitee, etc.
¿Posible? Ojalá sí.
Javi

**Comment by javipe** [comment]
Espectacular!!!!

**Comment by pr3ssh** [comment]
Si tiene pues se muestra y si no pues tira del nombre. THX!
