### ISSUE TITLE
¿No faltaría la categoría "Respondida" en el campo "Estado" del escáner para las preguntas?

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#92]
Hola @pr3ssh 

¿No faltaría la categoría "Respondida" en el campo "Estado" del escáner? Con las categorías actuales las preguntas no tienen ningún estado que aluda a sus posibles estados.

Otra opción es "doblar" las actuales de Aprobada y No Aprobada y poner Aprobada/Respondida y No aprobada/No respondida.

Javi

**Comment by joseEnrique** [comment]
¿Cuando haya respuesta en las preguntas que se ponga respondida en tramitación? ¿y cuando no No respondida?  @CIECODE  ¿eso es lo que indicas?

**Comment by javipe** [comment]
Hola @joseEnrique 
Sí. Es que semánticamente no había ninguna categoría dentro de "tramitación" que respondiera a las distintas situaciones de las preguntas. Además de "respondida" y "no respondida", supongo que también pueden ser "caducadas" o "retiradas", pero eso sí está previsto ya ahora.
Javi

**Comment by pr3ssh** [comment]
@joseEnrique Estta tarea esta relacionada con la #81
