### ISSUE TITLE
¿En qué momento introducir corrección de erratas detectadas en los diccionarios?

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#94]
Hola @pr3ssh 
En los próximos días vamos a estar acometiendo una revisión en profundidad de los resultados de las búsquedas de TIPI para detectar errores en los diccionarios que estén generando falsos positivos en los matchings y, por tanto, "ensuciando" los resultados de la herramienta. No creo que vayan a ser muchos y una vez hechas estas primeras correcciones, la idea es no reabrir los diccionarios en un buen periodo de tiempo.
Lo que quería consultarte es si ves factible que en algún momento pronto podamos lanzar de nuevo el escrapeo con los diccionarios limpios de las erratas detectadas y así comenzamos con todo en orden. Se podría avisar que por unas horas o un día la herramienta no va a estar operativa y no creo que sea un problema.
Abrazo.
Javi

**Comment by pr3ssh** [comment]
@CIECODE Cuando nos digais lo revisamos y le damos. Creo que preferiblemente es en el fin de semana.

**Comment by javipe** [comment]
Perfecto.
Pues vamos a darle duro a la revisión y lo hablamos. Por ahora son erratas mínimas, pero que es mejor que no estén.
Abrazo.
Javi
