### ISSUE TITLE
Error en prácticamente todas las búsqueda: el título no se corresponde con el link del Congreso que ofrecemos

### ISSUE THREAD

**Issue by javipe** [CIECODE-Madrid/tipi#99]
Hola @pr3ssh,
He comenzado la búsqueda de erratas y esta no es de los diccionarios sino de la información que suministramos:
- El acto: http://tipiciudadano.es/tipis/57e4f97bcc307251be03eeeb 
- supuestamente se refiere a "Solicitud de comparecencia del Ministro de Economía y Competitividad en funciones, ante la Comisión de Economía y Competitividad, para que informe sobre la representación de España en los Organismos Financieros Internacionales".
- sin embargo el link que ofrecemos en el Congreso te lleva a otra petición de comparecencia distinta: "Solicitud de comparecencia del Ministro de Fomento en funciones, ante la Comisión de Fomento, para informar sobre la negativa de ADIF a cumplir con los compromisos de inversión en Rodalies de Barcelona, asumidos en 2013 por el Ministerio de Fomento, los cuales identificaban las principales carencias de la red y planificaban inversiones por importe de 306 millones de euros para abordar las actuaciones más urgentes a llevar a cabo para garantizar la infraestructura, inversiones de las que el pasado mes de julio sólo se había ejecutado un 4,1% del total".

He mirado este acto con tanto detalle porque me parecía raro que estuviera etiquetado con tantos ámbitos y términos como está, así que quizá haya algo más ocurriendo con este acto además del tema del link.

**Comment by javipe** [comment]
Hola @pr3ssh 
He detectado otro acto más en el que ocurre lo mismo:
- El acto: http://tipiciudadano.es/tipis/57e4f962cc307251be03ede9.
- Supuestamente se refiere a: Solicitud de comparecencia del Ministro de Economía y Competitividad en funciones, ante la Comisión de Economía y Competitividad, para informar de las razones y de la situación en que se encuentra el procedimiento abierto por la Comisión Europea para sancionar a España y retener fondos europeos por incumplimiento del objetivo de déficit público.
- Sin embargo, el link que ofrecemos al Congreso nos lleva a otra solicitud de comparecencia distinta: "Solicitud de comparecencia de la Ministra de Empleo y Seguridad Social, ante la Comisión de Empleo y Seguridad Social, para informar sobre la implementación y el desarrollo de la iniciativa europea para facilitar el acceso de los jóvenes al mercado de trabajo conocida como Garantía Juvenil. (213/000018)"

**Comment by javipe** [comment]
Hola @pr3ssh 
No sé si antes estaba así o ha sido ahora, pero en la práctica totalidad de los actos, el link que ofrecemos al Congreso no tiene ninguna relación con el acto parlamentario de origen.

**Comment by javipe** [comment]
Hola @joseEnrique @pr3ssh 
Ya está funcionando bien. Supongo que ha sido cosa vuestra. Qué bien!
¿Qué había pasado? (respuesta adaptada a un ser mortal como yo ;).
Javi

**Comment by pr3ssh** [comment]
@CIECODE Creo que ha sido algo de cache pero lo estoy revisando en mi entorno.
